// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMWd5dN9xAqhX_3pzZASjHMaLGfKgEeUw',
    appId: '1:256806324440:web:4fa6f0a581771494f9afad',
    messagingSenderId: '256806324440',
    projectId: 'e-commerce-4adc6',
    authDomain: 'e-commerce-4adc6.firebaseapp.com',
    storageBucket: 'e-commerce-4adc6.firebasestorage.app',
    measurementId: 'G-X6E3ZMTVZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG8TN-gbu_lejyFV9BVtJ1sy7LyUY9hTk',
    appId: '1:256806324440:android:8656e2c98b3ff52af9afad',
    messagingSenderId: '256806324440',
    projectId: 'e-commerce-4adc6',
    storageBucket: 'e-commerce-4adc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0-14jDI22LQ0jnQjAPeARXtuhUam_JgI',
    appId: '1:256806324440:ios:e1ad702d69cbc029f9afad',
    messagingSenderId: '256806324440',
    projectId: 'e-commerce-4adc6',
    storageBucket: 'e-commerce-4adc6.firebasestorage.app',
    iosBundleId: 'com.example.molla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0-14jDI22LQ0jnQjAPeARXtuhUam_JgI',
    appId: '1:256806324440:ios:e1ad702d69cbc029f9afad',
    messagingSenderId: '256806324440',
    projectId: 'e-commerce-4adc6',
    storageBucket: 'e-commerce-4adc6.firebasestorage.app',
    iosBundleId: 'com.example.molla',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMWd5dN9xAqhX_3pzZASjHMaLGfKgEeUw',
    appId: '1:256806324440:web:a89168a8db7a654ff9afad',
    messagingSenderId: '256806324440',
    projectId: 'e-commerce-4adc6',
    authDomain: 'e-commerce-4adc6.firebaseapp.com',
    storageBucket: 'e-commerce-4adc6.firebasestorage.app',
    measurementId: 'G-X8R84KSPJB',
  );
}
